### ISSUE TITLE
'remappings' is a confusing word. Possibly rename to simply 'mapping'?

### ISSUE THREAD

**Issue by 33thou** [ros2/launch_ros#181]
I'm still getting familiar with the ROS ecosystem and community feedback mechanisms to feel free to point me in the right direction if this is the wrong place for this feedback.

I was going through the tutorial at https://index.ros.org/doc/ros2/Tutorials/Launch-Files/Creating-Launch-Files/

There is a parameter called 'remappings' to the `Node` object which seems to be incorrectly named. This parameter is simply a singular 'mapping' list of tuples.

**Comment by clalancette** [comment]
> There is a parameter called 'remappings' to the `Node` object which seems to be incorrectly named. This parameter is simply a singular 'mapping' list of tuples.

The thing is, we call it `remapping` in a lot of places.  For instance, the design article explicitly uses that term: http://design.ros2.org/articles/static_remapping.html .

So I think for consistency, the term `remappings` in launch_ros makes the most sense.

**Comment by 33thou** [comment]
makes sense, thanks!
