### ISSUE TITLE
test_composable_node_container.py fails with rmw_connext_cpp

### ISSUE THREAD

**Issue by brawner** [ros2/launch_ros#184]
This test has been failing for the past two weeks.

Example:
http://build.ros2.org/view/Rci/job/Rci__nightly-connext_ubuntu_focal_amd64/106/testReport/test_launch_ros.test.test_launch_ros.actions/test_composable_node_container/test_composable_node_container_in_group_with_launch_configuration_in_description/

Trying with CI, testing `--packages-select launch_ros` with `rmw_connext_cpp`
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=12724)](http://ci.ros2.org/job/ci_linux/12724/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=10438)](http://ci.ros2.org/job/ci_osx/10438/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=12671)](http://ci.ros2.org/job/ci_windows/12671/)

**Comment by jacobperron** [comment]
See https://github.com/ros2/launch_ros/pull/195 for a fix.
