### ISSUE TITLE
Declare dependencies on launch_{xml,yaml} parsers to make sure they're available

### ISSUE THREAD

**Issue by christophebedard** [ros2/launch_ros#255]
#### Feature description

In some cases, if a package uses/runs launch files through `ros2launch` or `launch_testing` and nothing declares a dependency on `launch_xml`/`launch_yaml`, then the XML/YAML parsers won't be available. This causes weird failures and the cause isn't obvious.

Some example packages do declare an `<exec_depend>` or `<test_depend>` on one of the parser packages (e.g. https://github.com/ros2/demos/blob/3af19c93c7abd9a83caca47de0780e941faeb22b/demo_nodes_cpp/package.xml#L26), but in general this is a bit unexpected.

See discussion under https://github.com/ros2/launch/pull/516#issuecomment-879445998

#### Implementation considerations

Simply declare `<exec_depend>`s on `launch_xml` and `launch_yaml` in `ros2launch` and `launch_testing` (note that the latter is not in this repo). This should cover most cases.

We can also declare and use a group dependency (like `launch_frontend_packages`) alongside the hard/direct dependencies. This would be similar to have is done with `rcl_logging_packages` (`rcl` depends on both the default logging implementation *and* the `rcl_logging_packages`group).

**Comment by christophebedard** [comment]
cc @hidmic want me to do it?

**Comment by hidmic** [comment]
That'd be great @christophebedard. I'll make it official.
