### ISSUE TITLE
:man_farmer: launch_testing_ros set_param_launch_test fails on Windows release

### ISSUE THREAD

**Issue by Blast545** [ros2/launch_ros#280]
## Bug report

**Required Info:**

- Operating System: Windows Release
- Installation type: Source
- Version or commit hash: 4bfd998ee32101467a8b5a80cdba0cd051678dbe
- DDS implementation: N/A
- Client library (if applicable): `rclpy`

#### Steps to reproduce issue
It's a test failure appearing in the `nightly_win_rel` jobs of the buildfarm.

https://ci.ros2.org/view/nightly/job/nightly_win_rel/2094/

#### Expected behavior
Test passes.

#### Actual behavior
The test `set_param_launch_test.TestFixture.test_set_parameter` fails with the following stacktrace:

```
==================================================================================================================================================
FAIL: set_param_launch_test.TestFixture.test_set_parameter
--------------------------------------------------------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ci\ws\src\ros2\launch_ros\launch_testing_ros\test\examples\set_param_launch_test.py", line 52, in test_set_parameter
    response = node.set_parameter(state=True)
  File "C:\ci\ws\src\ros2\launch_ros\launch_testing_ros\test\examples\set_param_launch_test.py", line 76, in set_parameter
    assert future.done(), 'Client request timed out'
AssertionError: Client request timed out
assert False
 +  where False = <bound method Future.done of <rclpy.task.Future object at 0x0000018AC59141C0>>()
 +    where <bound method Future.done of <rclpy.task.Future object at 0x0000018AC59141C0>> = <rclpy.task.Future object at 0x0000018AC59141C0>.done
```

It has failed in the latest 9 nightly jobs.

**Comment by Blast545** [comment]
The window hangs issues seems to be unrelated to this particular issue and will be tracked here:  https://github.com/ros2/launch_ros/issues/285

I'll close this issue for now.

**Comment by audrow** [comment]
Reopening as I saw this error here: https://ci.ros2.org/job/ci_windows/16088/.

**Comment by Blast545** [comment]
Some recent metrics about this error in the nightlies: 

The last time it happened on the Windows release job:
https://ci.ros2.org/view/nightly/job/nightly_win_rel/2118/ (Nov 15th, 1 build)

Before that 
https://ci.ros2.org/view/nightly/job/nightly_win_rel/2104/ (Nov 1st, 19 consecutive builds)

Last time it happened on the Windows repeated jobs:
https://ci.ros2.org/view/nightly/job/nightly_win_rep/2447/ (Dec 2nd, 21 consecutive builds)

**Comment by adityapande-1995** [comment]
Disabled the test on Windows here : https://github.com/ros2/examples/pull/333

**Comment by sloretz** [comment]
Reopening - I think this PR is about the launch_testing_ros `set_param_launch_test`, not `WaitForTopics`. I'm still seeing it in CI for https://github.com/ros2/rosidl_python/pull/149 (but I'm not seeing it fail on my Windows machine locally)

**Comment by adityapande-1995** [comment]
The test is disabled for windows : https://github.com/ros2/examples/blob/6e76f78950a949007825f623b38f8f2305eac387/launch_testing/launch_testing_examples/launch_testing_examples/set_param_launch_test.py#L43, maybe we need a new release of ``ros2/examples`` ?

**Comment by sloretz** [comment]
> The test is disabled for windows : https://github.com/ros2/examples/blob/6e76f78950a949007825f623b38f8f2305eac387/launch_testing/launch_testing_examples/launch_testing_examples/set_param_launch_test.py#L43, maybe we need a new release of ros2/examples ?

**Comment by mlanting** [comment]
I've seen this failure a couple times on my Ubuntu machine while repeatedly running tests in an attempt to recreate a different intermittent failure with one of the timer tests.
