### ISSUE TITLE
roslaunch fails reading yaml file

### ISSUE THREAD

**Issue by AndreasAZiegler** [ros2/launch_ros#29]
I working with ROS2 Dashing on Ubuntu Bionic. I want to pass parameters to a node with a yaml file.

While I was looking for a solution, I came across a solution for ROS2 crystal on this post https://stackoverflow.com/questions/53917469/how-to-launch-a-node-with-a-parameter-in-ros2.

Unfortunately, that does not seem to work under ROS2 dashing. I created a fork of the ROS2 realsense driver (https://github.com/AndreasAZiegler/ros2_intel_realsense/tree/serial_no_param/realsense_ros2_camera) and my goal is to be able to pass the serial number via a parameter. With

    ros2 run realsense_ros2_camera realsense_ros2_camera  __params:=/paht/to/config/parameters.yaml

passing the parameter works fine but when I start the node with the launch python file

    ros2 launch realsense_ros2_camera ros2_intel_realsense.launch.py

it ignores the parameter. The path to the parameters.yaml is correct (I print it in the launch python script).

**Comment by wjwwood** [comment]
Can you provide the launch file which is trying to pass the parameter file (ideally a link to a specific commit and not a branch which can change overtime)? I'll close this until there is an update. Sorry for the delay in replying initially.
