### ISSUE TITLE
--ros-args argument is always present in Node

### ISSUE THREAD

**Issue by samprt-heracles** [ros2/launch_ros#354]
I am trying to launch a node that requires common command line arguments. I added a Node() instance in my LaunchDescription which contains the `package`, `executable` and `arguments` attributes. However the launched node complains about not knowing about argument `--ros-args`. 
I thought it was the `ros_arguments` attribute in the Node that added the `--ros-args` argument to the launch command so I don't understand why I am getting this error.

I am running Ubuntu 22.04 and ROS2 Humble.

**Comment by clalancette** [comment]
Please open questions like this on https://answers.ros.org, which is our central Question and Answer site.  You'll get a better answer there, and it will be searchable for the future.

Make sure to include a lot of information on what platform you are using, which ROS distribution you are using, and the exact steps you took.
