### ISSUE TITLE
FeatureRequest: Add type hints to launch_testing_ros examples.

### ISSUE THREAD

**Issue by lexi-brt** [ros2/launch_ros#366]
#### Feature description
It would be nice if the examples for launch_testing_ros had type hints since it would be easier to read and understand the example. This is a request to add those type hints.

For example it's unclear what the talker and proc_output parameter types are here: https://github.com/ros2/launch_ros/blob/rolling/launch_testing_ros/test/examples/talker_listener_launch_test.py#L89

**Comment by clalancette** [comment]
Yes, agreed that would be nice.  I'll mark this as a "good first issue" and "help wanted".

**Comment by Relativiteit** [comment]
@lexi-brt and @clalancette  I would like to make this one of my first contributions!

**Comment by clalancette** [comment]
> @lexi-brt and @clalancette I would like to make this one of my first contributions!

Please go ahead and make the changes and open a pull request.  We're happy to review.

**Comment by yaswanth1701** [comment]
Hi @clalancette , I don't seen any PRs for this particular issue. So,can I work on this issue?

**Comment by clalancette** [comment]
> Hi @clalancette , I don't see any PRs for this particular issue. So,can I work on this issue?

Please go ahead and make the changes and open a pull request.  We are happy to review.
