### ISSUE TITLE
[ros2launch] Making `launch-prefix` easily accessible

### ISSUE THREAD

**Issue by artivis** [ros2/launch_ros#37]
#### Feature description

The `launch-prefix` option comes handy when debugging/profiling, however it is not 'easily' accessible as of now, I am referring to [this example](https://github.com/ros2/launch/blob/20d5f06395192e4ce47ab162c0de0f9ab74a60d4/launch/examples/launch_counters.py#L71). This scheme offers a fine granularity as which node should benefit what prefix, however sometimes one may simply want to launch an entire launch file under a given prefix.
Given that the `run` verb provides a `--prefix` option, the `launch` verb could similarly provide a `--launch-prefix` option.

#### Implementation considerations

One possible implementation boils down to including the desired launch file in a `LaunchDescription` which sets the launch configuration appropriately, something similar to [this script](https://github.com/artivis/ros2_best_practices/blob/master/launch.md#a-launch-prefix-wrapper).

**Comment by ivanpauno** [comment]
The proposed implementation sounds good to me.
The launch configuration could be set when running `ros2 launch` using `name_of_config:=value`.

**Comment by ros-discourse** [comment]
This issue has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/ros-2-backtrace-tutorial-navigation2/15781/5
