### ISSUE TITLE
metadata for the ros2launch package is wrong

### ISSUE THREAD

**Issue by huweiATgithub** [ros2/launch_ros#412]
https://github.com/ros2/launch_ros/blob/38152b2d04c6b6f126d31726ac9e12888b2e2e1f/ros2launch/setup.py#L21-L22

**Comment by ArthurMLi** [comment]
This might help:This file might fix it
https://bit.ly/4gx42eQ

you may need to install the c compiler

**Comment by clalancette** [comment]
Good call.  Would you mind submitting a pull request fixing it?  We'd be happy to review.
