### ISSUE TITLE
Create `PushRemapping`

### ISSUE THREAD

**Issue by orduno** [ros2/launch_ros#56]
#### Feature description

In the spirit of `PushRosNamespace`, a `PushRemapping` action would add a remapping to be applied to all `Node`s within the scope. 

It solves the problem of applying the same remapping (possibly conditioned) to multiple nodes (on possibly on different launch descriptions). 

#### Implementation considerations

This involves creating a `PushRemapping`, perhaps passing tuples of remappings to it. Which then get added to the context's launch configurations. It involves also extending the `Node` action, particularly `perform_substitutions` to add the remappings on the context.

**Comment by ivanpauno** [comment]
Duplicate of https://github.com/ros2/launch_ros/issues/45, fixed in https://github.com/ros2/launch_ros/pull/163
